let alldatawisata = [
  {
    id: 'wisata1',
    itemSrc: './img/kota-semarang/CandiGedongSongo.png',
    name: 'Candi Gedong Songo',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata2',
    itemSrc: './img/kota-semarang/CimoryOnTheValley.png',
    name: 'Cimory On The Valley',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata3',
    itemSrc: './img/kota-semarang/DusunSemilirEcoPark.png',
    name: 'Dusun Semilir Eco Park',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata4',
    itemSrc: './img/kota-semarang/LawangSewu.png',
    name: 'Lawang Sewu',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata5',
    itemSrc: './img/kota-semarang/SnowOwrld.png',
    name: 'Snow World',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata6',
    itemSrc: './img/kota-semarang/TamanBungaCelosia.png',
    name: 'Taman Bunga Celosia',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata7',
    itemSrc: './img/kota-semarang/TheGreatTempleOfSamPooKong.png',
    name: 'The Great Temple Of Sam Poo Kong',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata8',
    itemSrc: './img/kota-semarang/UmbulSidomukti.png',
    name: 'Umbul Sidomukti',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata9',
    itemSrc: './img/kota-pekalongan/BatangPark.png',
    name: 'Batang Park',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata10',
    itemSrc: './img/kota-pekalongan/BlackCanyon.png',
    name: 'Black Canyon',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata11',
    itemSrc: './img/kota-pekalongan/KaliPaingan.png',
    name: 'Kali Paingan',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './img/kota-pekalongan/MasjidAl-Fairus.png',
    name: 'Masjid Al-Fairus',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './img/kota-pekalongan/MuseumBatik.png',
    name: 'Museum Batik ',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './img/kota-pekalongan/PantaiPasirKencana.png',
    name: 'Pantai Pasir Kencana',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata15',
    itemSrc: './img/kota-pekalongan/TheMobyPark.png',
    name: 'The Moby Park',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata16',
    itemSrc: './img/kota-pekalongan/WisataBahariPPNP.png',
    name: 'Wisata Bahari PPNP',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata17',
    itemSrc: './img/kota-surakarta/DeTjolomadoe.png',
    name: 'De Tjo lomadoe',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata18',
    itemSrc: './img/kota-surakarta/GrojoganSewu.png',
    name: 'Grojogan Sewu',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata19',
    itemSrc: './img/kota-surakarta/KeratonSurakartaHadiningrat.png',
    name: 'Keraton Surakarta Hadiningrat',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata20',
    itemSrc: './img/kota-surakarta/LawuPark.png',
    name: 'Lawu Park',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata21',
    itemSrc: './img/kota-surakarta/MuseumBatikDanarHadi.png',
    name: 'Museum Batik Danar Hadi',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata22',
    itemSrc: './img/kota-surakarta/RumahAtsiri.png',
    name: 'Rumah Atsiri',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata23',
    itemSrc: './img/kota-surakarta/SoloSafari.png',
    name: 'Solo Safari',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata24',
    itemSrc: './img/kota-surakarta/TheHeritagePalace.png',
    name: 'The Heritage Palace',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata25',
    itemSrc: './img/kota-salatiga/AirTerjunKaliTingkir.png',
    name: 'Air Terjun Kali Tingkir',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata26',
    itemSrc: './img/kota-salatiga/BentengPendem.png',
    name: 'Benteng Pendem',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata27',
    itemSrc: './img/kota-salatiga/MataAirSenjoyo.png',
    name: 'Mata Air Senjoyo',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata28',
    itemSrc: './img/kota-salatiga/RawaPening.png',
    name: 'Rawa Pening',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata29',
    itemSrc: './img/kota-salatiga/SalokaThemePark.png',
    name: 'Saloka Theme Park',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata30',
    itemSrc: './img/kota-salatiga/Telomoyo.png',
    name: 'Telomoyo',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata31',
    itemSrc: './img/kota-salatiga/UmbulSidomukti.png',
    name: 'Umbul Sidomukti',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata32',
    itemSrc: './img/kota-magelang/AwangAwangSkyView.png',
    name: 'Awang Awang Sky View',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata33',
    itemSrc: './img/kota-magelang/BukitRhemaGerejaAyam.png',
    name: 'Bukit Rhema Gereja Ayam',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata34',
    itemSrc: './img/kota-magelang/CandiBorobudur.png',
    name: 'Candi Borobudur',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata35',
    itemSrc: './img/kota-magelang/PunthukSetumbu.png',
    name: 'Punthuk Setumbu',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata36',
    itemSrc: './img/kota-magelang/SvargaBumi.png',
    name: 'Svarga Bumi',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata37',
    itemSrc: './img/kota-magelang/TKLEcopark.png',
    name: 'TKL Ecopark',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata38',
    itemSrc: './img/kota-tegal/GerbangMasBahari.png',
    name: 'Gerbang Mas Bahari',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata39',
    itemSrc: './img/kota-tegal/GucikuHotWaterboom.png',
    name: 'Guciku Hot Waterboom',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata38',
    itemSrc: './img/kota-tegal/RitaParkTegal.png',
    name: 'Rita Park Tegal',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata38',
    itemSrc: './img/kota-tegal/TransStudioMiniTegal.png',
    name: 'Trans Studio Mini Tegal',
    idkota: 'Tegal',
    price: 350000,
  },
];

function getdata(id) {
  switch (id) {
    case 'all':
      return alldatawisata;
      break;

    default:
      return alldatawisata.filter((wisata) => wisata.idkota === id);
      break;
  }
}
