let alldatawisata = [
  {
    id: 'wisata1',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 1',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata2',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 1',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata3',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 1',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata4',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 1',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata5',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 1',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata6',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 1',
    idkota: 'Semarang',
    price: 350000,
  },
  {
    id: 'wisata7',
    itemSrc: './foto/salman.png',
    name: 'wisata kota 2',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata8',
    itemSrc: './foto/salman.png',
    name: 'wisata kota 2',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata9',
    itemSrc: './foto/salman.png',
    name: 'wisata kota 2',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata10',
    itemSrc: './foto/salman.png',
    name: 'wisata kota 2',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata11',
    itemSrc: './foto/salman.png',
    name: 'wisata kota 2',
    idkota: 'Pekalongan',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Sulton.png',
    name: 'wisata kota 3',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Sulton.png',
    name: 'wisata kota 3',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Sulton.png',
    name: 'wisata kota 3',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Sulton.png',
    name: 'wisata kota 3',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Sulton.png',
    name: 'wisata kota 3',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Sulton.png',
    name: 'wisata kota 3',
    idkota: 'Surakarta',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Fiqri.png',
    name: 'wisata kota 4',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Fiqri.png',
    name: 'wisata kota 4',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Fiqri.png',
    name: 'wisata kota 4',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Fiqri.png',
    name: 'wisata kota 4',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Fiqri.png',
    name: 'wisata kota 4',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Fiqri.png',
    name: 'wisata kota 4',
    idkota: 'Salatiga',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Aulia.png',
    name: 'wisata kota 5',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Aulia.png',
    name: 'wisata kota 5',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Aulia.png',
    name: 'wisata kota 5',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Aulia.png',
    name: 'wisata kota 5',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Aulia.png',
    name: 'wisata kota 5',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Aulia.png',
    name: 'wisata kota 5',
    idkota: 'Magelang',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 6',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 6',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 6',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata12',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 6',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata13',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 6',
    idkota: 'Tegal',
    price: 350000,
  },
  {
    id: 'wisata14',
    itemSrc: './foto/Nadira.png',
    name: 'wisata kota 6',
    idkota: 'Tegal',
    price: 350000,
  },
];

function getdata(id) {
  switch (id) {
    case 'all':
      return alldatawisata;
      break;

    default:
      return alldatawisata.filter((wisata) => wisata.idkota === id);
      break;
  }
}
